### ISSUE TITLE
node cli create-ca fails MacOS 10.15.3

### ISSUE THREAD

**Issue by levic92** [bifravst/aws#113]
```
 ERROR  create-ca failed!
 ERROR  CertificateValidationException: CA certificate is not valid. The CA certificate does not have the basicConstraints extension as true
```

To fix this I had to add this to `/etc/ssl/openssl.cnf`

```
[ v3_ca ]
basicConstraints = critical,CA:TRUE
subjectKeyIdentifier = hash
authorityKeyIdentifier = keyid:always,issuer:always
```

Then I had to modify createCA.ts in 2 places

https://github.com/bifravst/aws/blob/saga/cli/jitp/createCA.ts#L75
https://github.com/bifravst/aws/blob/saga/cli/jitp/createCA.ts#L110

```diff
        await run({
		command: 'openssl',
		args: [
			'req',
			'-x509',
			'-new',
			'-nodes',
			'-key',
			caFiles.key,
			'-sha256',
			'-days',
			'365',
+			'-extensions',
+			'v3_ca',
			'-out',
			caFiles.cert,
			'-subj',
			`/OU=${stackId}`,
		],
		log: debug,
	})

...

	await run({
		command: 'openssl',
		args: [
			'x509',
			'-req',
			'-in',
			caFiles.csr,
			'-CA',
			caFiles.cert,
			'-CAkey',
			caFiles.key,
			'-CAcreateserial',
			'-out',
			caFiles.verificationCert,
			'-days',
			'365',
			'-sha256',
+			'-extensions',
+			'v3_ca',
		],
		log: debug,
	})
```

I didn't create a PR for this issue because I don't know how it would affect different operating systems.

**Comment by coderbyheart** [comment]
This seems to be an issue with your system, in #115 I added tests on macOS Catalina 10.15 and they pass.

The e2e-tests include the certificate generation using the code you changed, so I assume it is related to a specific configuration of SSH on your system.
