### ISSUE TITLE
Cognito.SignInType.EMAIL not defined

### ISSUE THREAD

**Issue by cmedianu** [bifravst/aws#114]
Hi Markus,

I'm trying to install this code in AWS and I'm running into this. Any ideas?

npx cdk bootstrap
base-layer-1ed09e648420268d163bfddbe601299b9bd61b8f ✔️
processBatchMessages ✔️
createThingGroup ✔️
concatenateRawMessages ✔️
geolocateCellFromCacheStepFunction ✔️
geolocateCellFromDeviceLocationsStepFunction ✔️
geolocateCellFromUnwiredLabsStepFunction ✔️
cacheCellGeolocationStepFunction ✔️
geolocateCellFromCacheHttpApi ✔️
cacheCellGeolocationFromDeviceIfNewCell ✔️
addCellGeolocationHttpApi ✔️
TypeError: Cannot read property 'EMAIL' of undefined
    at new BifravstStack (/work/bifravst-aws/dist/cdk/stacks/Bifravst.js:33:44)
    at new BifravstApp (/work/bifravst-aws/dist/cdk/apps/Bifravst.js:9:9)
    at /work/bifravst-aws/dist/cdk/cloudformation.js:20:35
    at processTicksAndRejections (internal/process/task_queues.js:97:5)

cdk --version
1.27.0 (build a98c0b3)

**Comment by coderbyheart** [comment]
Thanks for reporting.

This is fixed in [v9.9.2](https://github.com/bifravst/aws/releases/tag/v9.9.2) via 092e312da714c8d33053a44d6c05b8503c1bf681
